#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Reintegros.Droid.Resource", IsApplication=true)]

namespace Reintegros.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int btnAttach = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int btnCancel = 2131099675;
			
			// aapt resource value: 0x7f060005
			public const int btnIngresar = 2131099653;
			
			// aapt resource value: 0x7f06001a
			public const int btnSubmit = 2131099674;
			
			// aapt resource value: 0x7f06000f
			public const int ddlMotivo = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int ddlPersonaAutorizante = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int ddlSubunidad = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int ddlUser = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int lblAutorizar = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int lblCliente = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int lblFecha = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int lblImporte = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int lblMotivo = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int lblPassword = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int lblPersonaAutorizante = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int lblSubproyecto = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int lblSubunidad = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int lblTitle = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int lblUser = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int lblUsuario = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int scrollView = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int txtAutorizar = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int txtCliente = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int txtFecha = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int txtImporte = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int txtPassword = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int txtSubproyecto = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int txtTitle = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int txtUsuario = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int AppTheme_Base = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
